feat: 内製 wrapper で `EvHandler::message` を書き直す
approvers/ichiyoAI pull request #176
Opened 2024-01-01 17:54 UTC by Nanai10a

2024-01-01 19:15 UTC, Nanai10a commented
それっぽく動くことを確認しました. Ready for Review!

2024-01-02 06:01 UTC, m1sk9 approved these changes

2024-01-02 06:01 UTC, m1sk9 commented on src/event.rs
> +                panic!();
No Context panic やめて

2024-01-02 06:02 UTC, m1sk9 requested changes
間違えた

2024-01-02 08:06 UTC, Nanai10a commented on src/event.rs
> +                panic!();
No Context panic やめた

2024-01-02 08:16 UTC, m1sk9 approved these changes

2024-01-02 08:16 UTC, merged